### ISSUE TITLE
"Unexpected token ." in Glitch

### ISSUE THREAD

**Issue by 1RB** [User9684/stupid-discord-badge#18]
```
/app/index.js:17
        if (interaction?.data?.name === 'lol') {
                        ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by 1RB** [comment]
got badge but this is still an issue
